# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/xroute/net_ordering.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/xroute/net_ordering.proto\x12\x13xroute.net_ordering\"\xc1\x01\n\x04Node\x12\x0e\n\x06maze_x\x18\x01 \x01(\x11\x12\x0e\n\x06maze_y\x18\x02 \x01(\x11\x12\x0e\n\x06maze_z\x18\x03 \x01(\x11\x12\x0f\n\x07point_x\x18\x04 \x01(\x11\x12\x0f\n\x07point_y\x18\x05 \x01(\x11\x12\x0f\n\x07point_z\x18\x06 \x01(\x11\x12+\n\x04type\x18\x07 \x01(\x0e\x32\x1d.xroute.net_ordering.NodeType\x12\x0f\n\x07is_used\x18\x08 \x01(\x08\x12\x0b\n\x03net\x18\t \x01(\r\x12\x0b\n\x03pin\x18\n \x01(\r\"\x1a\n\x07Initial\x12\x0f\n\x07task_id\x18\x01 \x01(\r\"\xaa\x01\n\x07Request\x12\r\n\x05\x64im_x\x18\x01 \x01(\r\x12\r\n\x05\x64im_y\x18\x02 \x01(\r\x12\r\n\x05\x64im_z\x18\x03 \x01(\r\x12(\n\x05nodes\x18\x04 \x03(\x0b\x32\x19.xroute.net_ordering.Node\x12\x18\n\x10reward_violation\x18\x05 \x01(\r\x12\x1a\n\x12reward_wire_length\x18\x06 \x01(\r\x12\x12\n\nreward_via\x18\x07 \x01(\r\"\x1d\n\x08Response\x12\x11\n\tnet_index\x18\x01 \x01(\r\"P\n\x04\x44one\x12\x18\n\x10reward_violation\x18\x05 \x01(\r\x12\x1a\n\x12reward_wire_length\x18\x06 \x01(\r\x12\x12\n\nreward_via\x18\x07 \x01(\r\"\xd4\x01\n\x07Message\x12/\n\x07initial\x18\x01 \x01(\x0b\x32\x1c.xroute.net_ordering.InitialH\x00\x12/\n\x07request\x18\x02 \x01(\x0b\x32\x1c.xroute.net_ordering.RequestH\x00\x12\x31\n\x08response\x18\x03 \x01(\x0b\x32\x1d.xroute.net_ordering.ResponseH\x00\x12)\n\x04\x64one\x18\x04 \x01(\x0b\x32\x19.xroute.net_ordering.DoneH\x00\x42\t\n\x07wrapper*0\n\x08NodeType\x12\x0c\n\x08\x42LOCKAGE\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\n\n\x06\x41\x43\x43\x45SS\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.xroute.net_ordering_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NODETYPE._serialized_start=781
  _NODETYPE._serialized_end=829
  _NODE._serialized_start=57
  _NODE._serialized_end=250
  _INITIAL._serialized_start=252
  _INITIAL._serialized_end=278
  _REQUEST._serialized_start=281
  _REQUEST._serialized_end=451
  _RESPONSE._serialized_start=453
  _RESPONSE._serialized_end=482
  _DONE._serialized_start=484
  _DONE._serialized_end=564
  _MESSAGE._serialized_start=567
  _MESSAGE._serialized_end=779
# @@protoc_insertion_point(module_scope)
